import OpenAI from "openai";

// the newest OpenAI model is "gpt-4o" which was released May 13, 2024. do not change this unless explicitly requested by the user
const openai = new OpenAI({ 
  apiKey: process.env.OPENAI_API_KEY || process.env.OPENAI_API_KEY_ENV_VAR || "sk-test-key"
});

export async function generateLiteratureReview(topic: string): Promise<string> {
  try {
    // Check if OpenAI API key is available
    if (!process.env.OPENAI_API_KEY) {
      throw new Error("OpenAI API key not configured. Please provide your API key to enable AI-powered content generation.");
    }

    const prompt = `Generate a comprehensive academic literature review on the topic: "${topic}".

The review should include:
1. Introduction section explaining the topic and its significance
2. Current state of research with specific examples and citations (you can create realistic academic citations)
3. Key findings and methodologies
4. Research gaps and future directions
5. Conclusion

Format the output as HTML with proper headings (h3, h4), paragraphs, and lists. Use professional academic language.
The content should be substantial (800-1200 words) and demonstrate thorough knowledge of the field.

Include realistic but fictitious citations in the format: (Author et al., Year).`;

    const response = await openai.chat.completions.create({
      model: "gpt-4o",
      messages: [
        {
          role: "system",
          content: "You are an expert academic researcher with extensive knowledge across multiple fields. Generate comprehensive, well-structured literature reviews that demonstrate deep understanding of academic topics."
        },
        {
          role: "user",
          content: prompt
        }
      ],
      max_tokens: 3000,
      temperature: 0.7,
    });

    const content = response.choices[0].message.content;
    if (!content) {
      throw new Error("No content generated by OpenAI");
    }

    return content;
  } catch (error: any) {
    console.error("Error generating literature review:", error);
    // Return an error message that will be displayed to the user
    return `<div class="p-4 border border-red-500 rounded-lg bg-red-50 text-red-800">
      <h3 class="font-semibold mb-2">Unable to Generate Literature Review</h3>
      <p>OpenAI API key is required to generate AI-powered content. Please provide your API key to enable this feature.</p>
      <p class="text-sm mt-2">Error: ${error.message}</p>
    </div>`;
  }
}

export async function generateArgumentExploration(
  topic: string, 
  initialThoughts?: string, 
  counterarguments?: string
): Promise<string> {
  try {
    // Check if OpenAI API key is available
    if (!process.env.OPENAI_API_KEY) {
      throw new Error("OpenAI API key not configured. Please provide your API key to enable AI-powered content generation.");
    }

    let prompt = `Generate a comprehensive argument exploration for the topic: "${topic}".

The exploration should include:
1. Multiple perspectives on the topic
2. Key arguments for different positions
3. Supporting evidence and reasoning
4. Potential counterarguments and rebuttals
5. Nuanced considerations and edge cases
6. A balanced conclusion that acknowledges complexity

Format the output as HTML with proper headings (h3, h4), paragraphs, and lists.
The content should be thorough (600-1000 words) and demonstrate critical thinking.`;

    if (initialThoughts) {
      prompt += `\n\nConsider these initial thoughts provided by the user: "${initialThoughts}"`;
    }

    if (counterarguments) {
      prompt += `\n\nAddress these potential counterarguments mentioned by the user: "${counterarguments}"`;
    }

    prompt += `\n\nProvide a well-balanced exploration that helps the user think through all aspects of this topic.`;

    const response = await openai.chat.completions.create({
      model: "gpt-4o",
      messages: [
        {
          role: "system",
          content: "You are an expert critical thinking facilitator who helps people explore complex topics from multiple angles. Generate balanced, thoughtful argument explorations that promote deeper understanding."
        },
        {
          role: "user",
          content: prompt
        }
      ],
      max_tokens: 2500,
      temperature: 0.8,
    });

    const content = response.choices[0].message.content;
    if (!content) {
      throw new Error("No content generated by OpenAI");
    }

    return content;
  } catch (error: any) {
    console.error("Error generating argument exploration:", error);
    // Return an error message that will be displayed to the user
    return `<div class="p-4 border border-red-500 rounded-lg bg-red-50 text-red-800">
      <h3 class="font-semibold mb-2">Unable to Generate Argument Exploration</h3>
      <p>OpenAI API key is required to generate AI-powered content. Please provide your API key to enable this feature.</p>
      <p class="text-sm mt-2">Error: ${error.message}</p>
    </div>`;
  }
}

export async function generatePersonalizedContent(
  type: "literature_review" | "argument_exploration",
  topic: string,
  userInput?: {
    initialThoughts?: string;
    counterarguments?: string;
    paperAbstracts?: string;
  }
): Promise<string> {
  try {
    if (type === "literature_review") {
      let prompt = `Generate a comprehensive academic literature review on: "${topic}".`;
      
      if (userInput?.initialThoughts) {
        prompt += `\n\nIncorporate and build upon these initial research findings: "${userInput.initialThoughts}"`;
      }
      
      if (userInput?.paperAbstracts) {
        prompt += `\n\nReference and expand on these paper abstracts provided by the user: "${userInput.paperAbstracts}"`;
      }
      
      return await generateLiteratureReview(topic);
    } else {
      return await generateArgumentExploration(topic, userInput?.initialThoughts, userInput?.counterarguments);
    }
  } catch (error: any) {
    console.error("Error generating personalized content:", error);
    throw new Error(`Failed to generate personalized content: ${error.message}`);
  }
}
